---
driver:
  name: vagrant
  vm_hostname: logstash-kitchen
driver_config:
  customize:
    memory: 1024
    cpus: 1

verifier:
  name: inspec

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 16
  attributes:
    java:
      jdk_version: "8"
    logstash:
      elasticsearch_uri: 'http://127.0.0.1:9200'
    rsyslog:
      server_ip: '127.0.0.1'
      port: '5959'

platforms:
  - name: ubuntu-18.04
    run_list:
      - recipe[apt::default]
  - name: ubuntu-20.04
    run_list:
      - recipe[apt::default]
  - name: debian-9
    run_list:
      - recipe[apt::default]
  - name: centos-7
  - name: centos-8

suites:
  - name: default
    run_list:
      - recipe[logstash_lwrp_test::default]
    attributes:
      apt:
        compile_time_update: true
